# Create README.md from template.md
README.md: # template.md - This will only run if template.md is updated, not other markdowns
	@echo "Making docs!"
	@echo "Made docs!"

# Create docs.yaml
docs.yaml:
	@echo "Making yaml!"
	@echo "Made yaml!"
